
---
Name: Tsuru
ModulesDir: modules
IncludeDir: include
SourceDir: source
RpxDir: +/rpxs
Defines:
  - NO_INTELLISENSE_HACK
  - Cemu
  - TSURU_DEBUG

Targets:
  US: ~
  EU: ~
  JP: ~
  Template/Tricky: # What if we made the game a bit more tricky...
    Defines:
      - TARGET_TRICKY
  Tricky_US:
    Extends: Tricky
    AddrMap: US
    BaseRpx: US
  Tricky_EU:
    Extends: Tricky
    AddrMap: EU
    BaseRpx: EU
  Tricky_JP:
    Extends: Tricky
    AddrMap: JP
    BaseRpx: JP
